import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ThemeProvider from "./context/Themecontext";
import ToggleTheme from "./components/ToggleTheme";
import DataContext from "./context/DataContext";
import { Header } from "./pages/header";
import ProjectContext from "./context/ProjectContext";
import Navbar from "./pages/navbar";
import Footer from "./pages/footer";
// import { CardProvider } from "./context/SingleProjectContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" style={{ fontFamily: "Inter, sans-serif" }}>
      <body>
        <DataContext>
          <ProjectContext>
            <ThemeProvider>
              <nav>
                <Header />
                {/* <Navbar /> */}
              </nav>
              <main>{children}</main>
              <Footer />
            </ThemeProvider>
          </ProjectContext>
          {/* </CardProvider> */}
        </DataContext>
      </body>
    </html>
  );
}
