import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ThemeProvider from "./context/Themecontext";
import ToggleTheme from "./components/ToggleTheme";
import DataContext from "./context/DataContext";
import { Header } from "./pages/header";
import ProjectContext from "./context/ProjectContext";
import Navbar from "./pages/navbar";
// import { CardProvider } from "./context/SingleProjectContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <DataContext>
          {/* <CardProvider> */}
          <ProjectContext>
            <ThemeProvider>
              <nav>
                <Header />
                <Navbar />
                {/* <ToggleTheme /> */}
              </nav>
              <main>{children}</main>
              <footer className="bg-black px-10 py-4 text-center">
                <h1 className="text-white font-xl text-center ">
                  Mrprince &copy;
                </h1>
              </footer>
            </ThemeProvider>
          </ProjectContext>
          {/* </CardProvider> */}
        </DataContext>
      </body>
    </html>
  );
}
