import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ThemeProvider from "./context/Themecontext";
import ToggleTheme from "./hooks/ToggleTheme";
import DataContext from "./context/DataContext";
import { Header } from "./components/header";
import ProjectContext from "./context/ProjectContext";
import Navbar from "./components/navbar";
import Footer from "./components/footer";
import { ProjectProvider } from "./context/NavLink";
// import { CardProvider } from "./context/SingleProjectContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" style={{ fontFamily: "Inter, sans-serif" }}>
      <body>
        <DataContext>
          <ProjectProvider>
            <ProjectContext>
              <ThemeProvider>
                <nav>
                  <Header />
                  {/* <Navbar /> */}
                </nav>
                <main>{children}</main>
                <Footer />
              </ThemeProvider>
            </ProjectContext>
          </ProjectProvider>
          {/* </CardProvider> */}
        </DataContext>
      </body>
    </html>
  );
}
